data = [
  {"input_text": "what is python?", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"python\"}"},
  {"input_text": "Explain recursion", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"recursion\"}"},
  {"input_text": "Tell me about supervised learning", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"supervised learning\"}"},
  {"input_text": "summarize the concept of Big O notation", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"Big O notation\"}"},
  {"input_text": "give me the key points about linked lists", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"linked lists\"}"},
  {"input_text": "Can you show an example of a Python class?", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"Python class example\"}"},
  {"input_text": "what's the difference between a list and a tuple in python", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"python list vs tuple\"}"},
  {"input_text": "how do sql joins work?", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"sql joins\"}"},
  {"input_text": "elaborate on neural networks", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"neural networks\"}"},
  {"input_text": "describe data normalization", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"data normalization\"}"},
  {"input_text": "info on gradient descent please", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"gradient descent\"}"},
  {"input_text": "how is machine learning used?", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"machine learning applications\"}"},
  {"input_text": "what are data structures?", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"data structures\"}"},
  {"input_text": "explain object oriented programming", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"object oriented programming\"}"},
  {"input_text": "summarize inheritance", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"inheritance\"}"},
  {"input_text": "quick overview of APIs", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"APIs\"}"},
  {"input_text": "tell me more", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": null}"}, 
  {"input_text": "explain that further", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": null}"}, 
  {"input_text": "why?", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": null}"},
  {"input_text": "what about unsupervised learning?", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"unsupervised learning\"}"},
  {"input_text": "Talk about Flask.", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"Flask\"}"},
  {"input_text": "What is REST?", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"REST\"}"},
  {"input_text": "Definition of polymorphism", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"polymorphism\"}"},
  {"input_text": "How are stacks used?", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"stacks usage\"}"},
  {"input_text": "Compare BFS and DFS", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"BFS vs DFS\"}"},
  {"input_text": "Summarise the main sorting algorithms", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"sorting algorithms\"}"},
  {"input_text": "Example of NoSQL database?", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"NoSQL database example\"}"},
  {"input_text": "What is NLP?", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"NLP\"}"},
  {"input_text": "Tell me about computer vision.", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"computer vision\"}"},
  {"input_text": "Details on scikit-learn please", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"scikit-learn\"}"},

  {"input_text": "quiz me on python lists", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"python lists\"}"},
  {"input_text": "Test my knowledge about recursion", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"recursion\"}"},
  {"input_text": "Ask me some questions about data structures", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"data structures\"}"},
  {"input_text": "I want to practice OOP concepts", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"OOP concepts\"}"},
  {"input_text": "What's my level for sorting algorithms?", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"sorting algorithms\"}"},
  {"input_text": "How well do I know Big O notation?", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"Big O notation\"}"},
  {"input_text": "Check my status on SQL basics", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"SQL basics\"}"},
  {"input_text": "Do I understand linked lists?", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"linked lists\"}"},
  {"input_text": "Let's see how I do on neural networks", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"neural networks\"}"},
  {"input_text": "Test me on classification vs regression", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"classification vs regression\"}"},
  {"input_text": "Am I ready for advanced algorithms?", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"advanced algorithms\"}"}, 
  {"input_text": "Check my python functions knowledge", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"python functions\"}"},
  {"input_text": "how am I doing with java basics?", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"java basics\"}"},
  {"input_text": "practice arrays", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"arrays\"}"},
  {"input_text": "quiz time for databases", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"databases\"}"},
  {"input_text": "ask me about REST APIs", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"REST APIs\"}"},
  {"input_text": "status check on supervised learning", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"supervised learning\"}"},
  {"input_text": "what is my progress on NLP?", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"NLP\"}"},
  {"input_text": "challenge me on pandas", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"pandas\"}"},
  {"input_text": "let's practice javascript variables", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"javascript variables\"}"},
  {"input_text": "how's my understanding of memory management?", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"memory management\"}"},
  {"input_text": "ask another question", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": null}"},
  {"input_text": "next one", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": null}"}, 

  {"input_text": "Review python data types for me", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": \"python data types\"}"},
  {"input_text": "Let's go over loops again", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": \"loops\"}"},
  {"input_text": "I need to review my weakest subject", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": null}"},
  {"input_text": "Review something I learned a while ago", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": null}"},
  {"input_text": "Help me revise binary search", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": \"binary search\"}"},
  {"input_text": "Go over the oldest thing I learned about AI", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": null}"},
  {"input_text": "Refresh my memory on hash maps", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": \"hash maps\"}"},
  {"input_text": "let's review what we covered yesterday about databases", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": \"databases\"}"}, 
  {"input_text": "review the basics", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": null}"},
  {"input_text": "review unsupervised learning", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": \"unsupervised learning\"}"},
  {"input_text": "need a refresher on SQL", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": \"SQL\"}"},
  {"input_text": "review the important stuff", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": null}"},
  {"input_text": "go over that topic from last week", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": null}"}, 

  {"input_text": "Hi", "target_json": "{\"intent\": \"OTHER\", \"topic\": null}"},
  {"input_text": "Hello there", "target_json": "{\"intent\": \"OTHER\", \"topic\": null}"},
  {"input_text": "Hey bot", "target_json": "{\"intent\": \"OTHER\", \"topic\": null}"},
  {"input_text": "Thanks", "target_json": "{\"intent\": \"OTHER\", \"topic\": null}"},
  {"input_text": "Thank you very much", "target_json": "{\"intent\": \"OTHER\", \"topic\": null}"},
  {"input_text": "OK", "target_json": "{\"intent\": \"OTHER\", \"topic\": null}"},
  {"input_text": "Got it", "target_json": "{\"intent\": \"OTHER\", \"topic\": null}"},
  {"input_text": "Sounds good", "target_json": "{\"intent\": \"OTHER\", \"topic\": null}"},
  {"input_text": "Bye", "target_json": "{\"intent\": \"OTHER\", \"topic\": null}"},
  {"input_text": "Goodbye", "target_json": "{\"intent\": \"OTHER\", \"topic\": null}"},
  {"input_text": "See you later", "target_json": "{\"intent\": \"OTHER\", \"topic\": null}"},
  {"input_text": "That was helpful", "target_json": "{\"intent\": \"OTHER\", \"topic\": null}"},
  {"input_text": "Interesting point", "target_json": "{\"intent\": \"OTHER\", \"topic\": null}"},
  {"input_text": "What can you do?", "target_json": "{\"intent\": \"OTHER\", \"topic\": null}"}, 
  {"input_text": "Can you help me?", "target_json": "{\"intent\": \"OTHER\", \"topic\": null}"}, 
  {"input_text": "asdfg hjkl", "target_json": "{\"intent\": \"OTHER\", \"topic\": null}"}, 
  {"input_text": "Tell me a joke", "target_json": "{\"intent\": \"OTHER\", \"topic\": null}"}, 


  {"input_text": "python dictionary methods", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"python dictionary methods\"}"},
  {"input_text": "how to implement a stack in java", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"java stack implementation\"}"},
  {"input_text": "summary of overfitting", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"overfitting\"}"},
  {"input_text": "Could you define 'process' in operating systems?", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"operating systems process definition\"}"},
  {"input_text": "Use cases for MongoDB", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"MongoDB use cases\"}"},

  {"input_text": "I'm ready for some questions on CSS selectors", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"CSS selectors\"}"},
  {"input_text": "evaluate my understanding of Flask routes", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"Flask routes\"}"},
  {"input_text": "my status regarding numpy arrays", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"numpy arrays\"}"},
  {"input_text": "Am I good with javascript promises?", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"javascript promises\"}"},
  {"input_text": "I'd like to practice C++ pointers", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"C++ pointers\"}"},

  {"input_text": "revisit HTML forms", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": \"HTML forms\"}"},
  {"input_text": "let's review the stuff i found difficult", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": null}"},
  {"input_text": "need to brush up on deep learning basics", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": \"deep learning basics\"}"},
  {"input_text": "review the oldest cs concept i learned", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": null}"},
  {"input_text": "go over file systems again", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": \"file systems\"}"},

  {"input_text": "Can you compare Python and Java?", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"Python vs Java\"}"},
  {"input_text": "What are the main principles of functional programming?", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"functional programming principles\"}"},
  {"input_text": "Summarize the ACID properties in databases.", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"ACID properties databases\"}"},
  {"input_text": "Give me an example of polymorphism in C++.", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"C++ polymorphism example\"}"},
  {"input_text": "Need help understanding pointers.", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"pointers\"}"},
  {"input_text": "How is data visualized?", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"data visualization\"}"},
  {"input_text": "Explain NLP tokenization.", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"NLP tokenization\"}"},
  {"input_text": "What's a convolutional neural network?", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"convolutional neural network\"}"},
  {"input_text": "Tell me about the significance of p-value.", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"p-value significance\"}"},
  {"input_text": "Show me some pandas DataFrame operations.", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"pandas DataFrame operations\"}"},
  {"input_text": "How does virtual memory work?", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"virtual memory\"}"},
  {"input_text": "Explain threads vs processes.", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"threads vs processes\"}"},
  {"input_text": "What is HTTP?", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"HTTP\"}"},
  {"input_text": "Summarize the basics of git.", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"git basics\"}"},
  {"input_text": "I need to understand closures in JavaScript.", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"JavaScript closures\"}"},
  {"input_text": "Provide an overview of cloud computing models.", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"cloud computing models\"}"},
  {"input_text": "Describe the different types of machine learning.", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"types of machine learning\"}"},
  {"input_text": "What are activation functions?", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"activation functions\"}"},
  {"input_text": "Explain database indexing.", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"database indexing\"}"},
  {"input_text": "What's the point of CSS?", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"CSS purpose\"}"},
  {"input_text": "Tell me more about arrays.", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"arrays\"}"},
  {"input_text": "How do compilers work?", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"compilers\"}"},
  {"input_text": "What is supervised learning used for?", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"supervised learning use cases\"}"},
  {"input_text": "Explain clustering algorithms.", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"clustering algorithms\"}"},
  {"input_text": "Give me a summary of reinforcement learning.", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"reinforcement learning\"}"},
  {"input_text": "Tell me the difference between classification and regression", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"classification vs regression\"}"},
  {"input_text": "What is overfitting?", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"overfitting\"}"},
  {"input_text": "How is model performance evaluated in ML?", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"ML model evaluation\"}"},
  {"input_text": "What are lambda functions in Python?", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"Python lambda functions\"}"},
  {"input_text": "Describe network protocols.", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"network protocols\"}"},
  {"input_text": "Can you elaborate?", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": null}"},
  {"input_text": "Explain more please", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": null}"},
  {"input_text": "Go deeper into that", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": null}"},
  {"input_text": "What else?", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": null}"},

  {"input_text": "Let's do a quick test on network protocols.", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"network protocols\"}"},
  {"input_text": "Am I good with CSS fundamentals?", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"CSS fundamentals\"}"},
  {"input_text": "I want to practice writing SQL queries.", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"SQL queries\"}"},
  {"input_text": "What's my mastery of React components?", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"React components\"}"},
  {"input_text": "Check my knowledge regarding data warehousing.", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"data warehousing\"}"},
  {"input_text": "Ask me something about OS scheduling.", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"OS scheduling\"}"},
  {"input_text": "How proficient am I with git branches?", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"git branches\"}"},
  {"input_text": "Test me on ML evaluation metrics.", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"ML evaluation metrics\"}"},
  {"input_text": "Status update on data cleaning techniques.", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"data cleaning techniques\"}"},
  {"input_text": "How is my progress with TensorFlow?", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"TensorFlow\"}"},
  {"input_text": "I need to test my Java exception handling.", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"Java exception handling\"}"},
  {"input_text": "Do I know enough about cybersecurity basics?", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"cybersecurity basics\"}"},
  {"input_text": "Quiz me on algorithm complexity.", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"algorithm complexity\"}"},
  {"input_text": "Check my level on dynamic programming.", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"dynamic programming\"}"},
  {"input_text": "Let's practice graph traversal.", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"graph traversal\"}"},
  {"input_text": "Test my web sockets knowledge.", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"web sockets\"}"},
  {"input_text": "How much do I remember about heaps?", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"heaps\"}"},
  {"input_text": "Quiz about C++ templates", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"C++ templates\"}"},
  {"input_text": "What's my proficiency in pandas?", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"pandas\"}"},
  {"input_text": "Test me.", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": null}"}, 
  {"input_text": "Ask me some stuff.", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": null}"},
  {"input_text": "What's my status?", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": null}"},
  {"input_text": "Check my level", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": null}"},
  {"input_text": "Can you ask me something else?", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": null}"},
  {"input_text": "Another question please", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": null}"},
  {"input_text": "Let's test that", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": null}"},
  {"input_text": "How well do I grasp binary trees?", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"binary trees\"}"},
  {"input_text": "Test me on JavaScript async await", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"JavaScript async await\"}"},
  {"input_text": "My level for computer networks?", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"computer networks\"}"},
  {"input_text": "Quiz on Linux commands", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"Linux commands\"}"},

  {"input_text": "Revisit virtual memory concepts.", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": \"virtual memory concepts\"}"},
  {"input_text": "I forgot about binary trees, let's review.", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": \"binary trees\"}"},
  {"input_text": "Go over the subjects I know least well.", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": null}"},
  {"input_text": "Review the last topic we discussed.", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": null}"}, 
  {"input_text": "Can we do a quick review of APIs?", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": \"APIs\"}"},
  {"input_text": "Brush up on time complexity.", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": \"time complexity\"}"},
  {"input_text": "Need to review database normalization.", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": \"database normalization\"}"},
  {"input_text": "Let's review sorting.", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": \"sorting\"}"},
  {"input_text": "Go over hash tables again.", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": \"hash tables\"}"},
  {"input_text": "Review the weakest AI topic for me.", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": null}"},
  {"input_text": "I want to revise Python loops.", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": \"Python loops\"}"},
  {"input_text": "Quick review on functions.", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": \"functions\"}"},
  {"input_text": "Review oldest data structure.", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": null}"},
  {"input_text": "Need a refresher on classes.", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": \"classes\"}"},
  {"input_text": "Review.", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": null}"}, 
  {"input_text": "Let's revise", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": null}"},
  {"input_text": "Go over polymorphism.", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": \"polymorphism\"}"},
  {"input_text": "Help me review web dev basics.", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": \"web dev basics\"}"},
  {"input_text": "Revise OS concepts.", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": \"OS concepts\"}"},
  {"input_text": "Review machine learning workflows.", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": \"machine learning workflows\"}"},

  {"input_text": "Cool.", "target_json": "{\"intent\": \"OTHER\", \"topic\": null}"},
  {"input_text": "Alright then.", "target_json": "{\"intent\": \"OTHER\", \"topic\": null}"},
  {"input_text": "Not right now.", "target_json": "{\"intent\": \"OTHER\", \"topic\": null}"},
  {"input_text": "Maybe later.", "target_json": "{\"intent\": \"OTHER\", \"topic\": null}"},
  {"input_text": "Is this bot helpful?", "target_json": "{\"intent\": \"OTHER\", \"topic\": null}"}, 
  {"input_text": "Who made you?", "target_json": "{\"intent\": \"OTHER\", \"topic\": null}"},
  {"input_text": "What time is it?", "target_json": "{\"intent\": \"OTHER\", \"topic\": null}"},
  {"input_text": "Blah blah blah", "target_json": "{\"intent\": \"OTHER\", \"topic\": null}"},
  {"input_text": "Stop.", "target_json": "{\"intent\": \"OTHER\", \"topic\": null}"},
  {"input_text": "Wait.", "target_json": "{\"intent\": \"OTHER\", \"topic\": null}"},
  {"input_text": "That's wrong.", "target_json": "{\"intent\": \"OTHER\", \"topic\": null}"}, 
  {"input_text": "I disagree.", "target_json": "{\"intent\": \"OTHER\", \"topic\": null}"},
  {"input_text": "Let's talk about something else.", "target_json": "{\"intent\": \"OTHER\", \"topic\": null}"},
  {"input_text": "Can you sing a song?", "target_json": "{\"intent\": \"OTHER\", \"topic\": null}"},
  {"input_text": "Good bot.", "target_json": "{\"intent\": \"OTHER\", \"topic\": null}"},
  {"input_text": "This is fun.", "target_json": "{\"intent\": \"OTHER\", \"topic\": null}"},
  {"input_text": "What's the weather?", "target_json": "{\"intent\": \"OTHER\", \"topic\": null}"},
  {"input_text": "Can you order pizza?", "target_json": "{\"intent\": \"OTHER\", \"topic\": null}"},
  {"input_text": "What is your name?", "target_json": "{\"intent\": \"OTHER\", \"topic\": null}"},
  {"input_text": "Are you sentient?", "target_json": "{\"intent\": \"OTHER\", \"topic\": null}"},
  # --- Batch 2: More Examples ---
  # GET_INFORMATION
  {"input_text": "Demonstrate bubble sort.", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"bubble sort\"}"},
  {"input_text": "Could you illustrate how linked lists store data?", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"linked lists data storage\"}"},
  {"input_text": "What are the practical uses of graph algorithms?", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"graph algorithms use cases\"}"},
  {"input_text": "Summarize the difference between supervised and reinforcement learning.", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"supervised vs reinforcement learning\"}"},
  {"input_text": "Key points about API rate limiting?", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"API rate limiting\"}"},
  {"input_text": "Tell me about Python decorators.", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"Python decorators\"}"},
  {"input_text": "Show me how to handle file I/O in Java.", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"Java file I/O\"}"},
  {"input_text": "Explain the concept of threads.", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"threads\"}"},
  {"input_text": "Compare SQL and NoSQL databases again.", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"SQL vs NoSQL databases\"}"},
  {"input_text": "What is feature engineering in ML?", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"ML feature engineering\"}"},
  {"input_text": "Need details on network layers.", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"network layers\"}"},
  {"input_text": "How is memory allocated by the OS?", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"OS memory allocation\"}"},
  {"input_text": "What's the purpose of an OS kernel?", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"OS kernel purpose\"}"},
  {"input_text": "Give me a quick summary of blockchain.", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"blockchain\"}"},
  {"input_text": "How are decision trees used?", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"decision trees usage\"}"},
  {"input_text": "Explain hash collisions.", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"hash collisions\"}"},
  {"input_text": "What are Python generators?", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"Python generators\"}"},
  {"input_text": "Tell me about virtual environments in Python.", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"Python virtual environments\"}"},
  {"input_text": "Summarize web accessibility principles.", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"web accessibility principles\"}"},
  {"input_text": "Explain CSS specificity.", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"CSS specificity\"}"},
  {"input_text": "What is agile methodology?", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"agile methodology\"}"},
  {"input_text": "Describe unit testing.", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"unit testing\"}"},
  {"input_text": "How does TCP work?", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"TCP\"}"},
  {"input_text": "What is bandwidth?", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"bandwidth\"}"},
  {"input_text": "Explain latency.", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"latency\"}"},
  {"input_text": "Give me an example of unsupervised learning.", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"unsupervised learning example\"}"},
  {"input_text": "What is deep learning?", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"deep learning\"}"},
  {"input_text": "Tell me about natural language generation.", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"natural language generation\"}"},
  {"input_text": "Summarize the concept of bias in AI.", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"AI bias\"}"},
  {"input_text": "What are evaluation metrics for classification?", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"classification evaluation metrics\"}"},
  {"input_text": "Like what?", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": null}"},
  {"input_text": "Can you give me specifics?", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": null}"},
  {"input_text": "How so?", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": null}"},
  {"input_text": "Explain that last concept.", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": null}"}, # Backend uses history
  {"input_text": "What does that mean?", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": null}"},
  {"input_text": "Summarize the key ideas.", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": null}"}, # Backend needs history for topic
  {"input_text": "What are the advantages of using Java?", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"Java advantages\"}"},
  {"input_text": "Describe dependency injection.", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"dependency injection\"}"},
  {"input_text": "What is cloud native?", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"cloud native\"}"},
  {"input_text": "Tell me about microservices architecture.", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"microservices architecture\"}"},
  {"input_text": "How does Kubernetes work?", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"Kubernetes\"}"},
  {"input_text": "Explain Docker.", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"Docker\"}"},
  {"input_text": "What is Infrastructure as Code?", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"Infrastructure as Code\"}"},
  {"input_text": "Summarize CI/CD pipelines.", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"CI/CD pipelines\"}"},
  {"input_text": "What are the different types of software testing?", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"software testing types\"}"},
  {"input_text": "How to prevent SQL injection?", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"SQL injection prevention\"}"},
  {"input_text": "Explain public key cryptography.", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"public key cryptography\"}"},
  {"input_text": "What is hashing used for in security?", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"hashing in security\"}"},
  {"input_text": "Tell me about different database paradigms.", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"database paradigms\"}"},
  {"input_text": "Summarize MapReduce.", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"MapReduce\"}"},

  # --- More MANAGE_KNOWLEDGE ---
  {"input_text": "I want to check my grasp of asymptotic notation.", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"asymptotic notation\"}"},
  {"input_text": "Let's have a pop quiz on recursion.", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"recursion\"}"},
  {"input_text": "Assess my knowledge of CSS flexbox.", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"CSS flexbox\"}"},
  {"input_text": "How am I doing with object-oriented principles?", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"object-oriented principles\"}"},
  {"input_text": "Hit me with some questions about database normalization.", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"database normalization\"}"},
  {"input_text": "Time for a test on Python generators.", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"Python generators\"}"},
  {"input_text": "Check my C++ memory management level.", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"C++ memory management\"}"},
  {"input_text": "Can I answer questions about gradient descent?", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"gradient descent\"}"},
  {"input_text": "Evaluate my skills with React hooks.", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"React hooks\"}"},
  {"input_text": "Practice problems for dynamic programming.", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"dynamic programming\"}"},
  {"input_text": "Test my understanding of data types.", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"data types\"}"},
  {"input_text": "How well do I really know loops?", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"loops\"}"},
  {"input_text": "Let's see my status on API design.", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"API design\"}"},
  {"input_text": "Ask me about multithreading.", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"multithreading\"}"},
  {"input_text": "Quiz on machine learning basics", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"machine learning basics\"}"},
  {"input_text": "How's my knowledge of SQL aggregate functions?", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"SQL aggregate functions\"}"},
  {"input_text": "Check my understanding of polymorphism.", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"polymorphism\"}"},
  {"input_text": "I want to try some questions on computer vision.", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"computer vision\"}"},
  {"input_text": "What's my level on data analysis with pandas?", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"data analysis pandas\"}"},
  {"input_text": "Test me on web security vulnerabilities.", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"web security vulnerabilities\"}"},
  {"input_text": "Ask me about linked list operations.", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"linked list operations\"}"},
  {"input_text": "Check my progress on AI ethics.", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"AI ethics\"}"},
  {"input_text": "Quiz me about trees.", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"trees\"}"},
  {"input_text": "How good am I at debugging?", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"debugging\"}"},
  {"input_text": "Test my knowledge.", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": null}"},
  {"input_text": "Check my status.", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": null}"},
  {"input_text": "Let's do some questions.", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": null}"},
  {"input_text": "Ask me one more.", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": null}"},
  {"input_text": "Next question.", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": null}"},
  {"input_text": "I'm ready for another.", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": null}"},

  # --- More REQUEST_REVIEW ---
  {"input_text": "Revisit classes and objects.", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": \"classes and objects\"}"},
  {"input_text": "Go over Big O complexity again.", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": \"Big O complexity\"}"},
  {"input_text": "I need to review the concepts I got wrong last time.", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": null}"},
  {"input_text": "Can we review the oldest ML topic?", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": null}"},
  {"input_text": "Let's do a quick refresher on network sockets.", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": \"network sockets\"}"},
  {"input_text": "Go over stacks and queues.", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": \"stacks and queues\"}"},
  {"input_text": "Brush up on Python exception handling.", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": \"Python exception handling\"}"},
  {"input_text": "Review my least understood topic.", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": null}"},
  {"input_text": "Let's revise Java syntax.", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": \"Java syntax\"}"},
  {"input_text": "Review REST principles.", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": \"REST principles\"}"},
  {"input_text": "Need to review database transactions.", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": \"database transactions\"}"},
  {"input_text": "Go over graph algorithms.", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": \"graph algorithms\"}"},
  {"input_text": "Revisit neural network layers.", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": \"neural network layers\"}"},
  {"input_text": "Let's review CSS box model.", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": \"CSS box model\"}"},
  {"input_text": "Refresh memory on data cleaning.", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": \"data cleaning\"}"},
  {"input_text": "Review the oldest programming concept.", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": null}"},
  {"input_text": "Help me revise my weakest data science topic.", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": null}"},
  {"input_text": "Review concurrency.", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": \"concurrency\"}"},
  {"input_text": "Go over security basics again.", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": \"security basics\"}"},
  {"input_text": "I want to review OOP.", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": \"OOP\"}"},

  # --- More OTHER ---
  {"input_text": "That's clear now.", "target_json": "{\"intent\": \"OTHER\", \"topic\": null}"},
  {"input_text": "Good explanation.", "target_json": "{\"intent\": \"OTHER\", \"topic\": null}"},
  {"input_text": "Never mind.", "target_json": "{\"intent\": \"OTHER\", \"topic\": null}"},
  {"input_text": "What else can this bot do?", "target_json": "{\"intent\": \"OTHER\", \"topic\": null}"},
  {"input_text": "Are you an AI?", "target_json": "{\"intent\": \"OTHER\", \"topic\": null}"},
  {"input_text": "Where did you get that info?", "target_json": "{\"intent\": \"OTHER\", \"topic\": null}"},
  {"input_text": "Can you write code for me?", "target_json": "{\"intent\": \"OTHER\", \"topic\": null}"}, # Could be GET_INFORMATION depending on how you handle it
  {"input_text": "Make it stop.", "target_json": "{\"intent\": \"OTHER\", \"topic\": null}"},
  {"input_text": "Fascinating.", "target_json": "{\"intent\": \"OTHER\", \"topic\": null}"},
  {"input_text": "I don't get it.", "target_json": "{\"intent\": \"OTHER\", \"topic\": null}"}, # Maybe trigger re-explanation? Treat as OTHER for NLU.
  {"input_text": "That's complex.", "target_json": "{\"intent\": \"OTHER\", \"topic\": null}"},
  {"input_text": "Sure.", "target_json": "{\"intent\": \"OTHER\", \"topic\": null}"},
  {"input_text": "No thanks.", "target_json": "{\"intent\": \"OTHER\", \"topic\": null}"},
  {"input_text": "Exit.", "target_json": "{\"intent\": \"OTHER\", \"topic\": null}"},
  {"input_text": "Quit now.", "target_json": "{\"intent\": \"OTHER\", \"topic\": null}"},
  {"input_text": "That is incorrect.", "target_json": "{\"intent\": \"OTHER\", \"topic\": null}"}, # User feedback
  {"input_text": "What's your source?", "target_json": "{\"intent\": \"OTHER\", \"topic\": null}"}, # Maybe GET_INFORMATION later
  {"input_text": "Tell me a story.", "target_json": "{\"intent\": \"OTHER\", \"topic\": null}"},
  {"input_text": "What day is it?", "target_json": "{\"intent\": \"OTHER\", \"topic\": null}"},
  {"input_text": "My name is Bob.", "target_json": "{\"intent\": \"OTHER\", \"topic\": null}"},

  # --- More combinations and edge cases ---
  {"input_text": "Could you quiz me after explaining linked lists?", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"linked lists\"}"}, # NLU focuses on first action
  {"input_text": "Check my knowledge on Python, then ask some questions.", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"Python\"}"}, # NLU gets intent, backend might need logic for sequence
  {"input_text": "Review the oldest topic, then summarize it.", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": null}"}, # NLU focuses on first action
  {"input_text": "What is a list? Then quiz me.", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"list\"}"},
  {"input_text": "Can you test my understanding?", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": null}"}, # Needs clarification
  {"input_text": "Review status", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": null}"}, # Ambiguous, likely default review
  {"input_text": "Information about AI safety", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"AI safety\"}"},
  {"input_text": "Let's manage my knowledge on databases.", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"databases\"}"},
  {"input_text": "Status check required for loops.", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": \"loops\"}"},
  {"input_text": "Quick quiz on that topic", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": null}"}, # Needs context
  {"input_text": "Summarize context switching.", "target_json": "{\"intent\": \"GET_INFORMATION\", \"topic\": \"context switching\"}"},
  {"input_text": "Help me revise the difficult parts.", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": null}"},
  {"input_text": "What is the status?", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": null}"},
  {"input_text": "Proceed with the test.", "target_json": "{\"intent\": \"MANAGE_KNOWLEDGE\", \"topic\": null}"},
  {"input_text": "Continue review.", "target_json": "{\"intent\": \"REQUEST_REVIEW\", \"topic\": null}"},
]

import json
with open("dataset_intent.jsonl", "w") as f:
    for item in data:
         f.write(json.dumps(item) + "\n")