import os
from dotenv import load_dotenv

load_dotenv()

HF_TOKEN = os.getenv("HF_TOKEN")
MONGO_CONNECTION_STRING = os.getenv("MONGO_CONNECTION_STRING")
DB_NAME = os.getenv("DB_NAME")
DOCS_COLLECTION = os.getenv("DOCS_COLLECTION")
USER_COLLECTION = os.getenv("USER_COLLECTION")
EMBEDDING_MODEL_NAME = os.getenv("EMBEDDING_MODEL_NAME")
BASE_LLM_NAME = os.getenv("BASE_LLM_NAME")
ADAPTER_NAME = os.getenv("ADAPTER_NAME")
VECTOR_INDEX_NAME = os.getenv("VECTOR_INDEX_NAME")
JWT_SECRET_KEY=os.getenv("JWT_SECRET_KEY")
JWT_ALGORITHM=os.getenv("JWT_ALGORITHM")
ACCESS_TOKEN_EXPIRE_MINUTES=os.getenv("ACCESS_TOKEN_EXPIRE_MINUTES")
GPT_KEY=os.getenv("GPT_KEY")